name: Rust CI

on:
  push:
    branches: 
      - "main"
      - "feature/**"
  pull_request:
    branches: 
      - "main"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
        # Exclude clippy and fmt checks on beta and nightly to avoid redundancy
        exclude:
          - toolchain: beta
          - toolchain: nightly

    steps:
    - uses: actions/checkout@v3
    - name: Set up Rust toolchain
      run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Lint with clippy
      if: matrix.toolchain == 'stable' # Run clippy only on stable
      run: |
        rustup component add clippy
        cargo clippy -- -D warnings
    - name: Check formatting with rustfmt
      if: matrix.toolchain == 'stable' # Run rustfmt only on stable
      run: |
        rustup component add rustfmt
        cargo fmt -- --check
